/*
 * Insolar Block Explorer API
 *
 * BE description 
 *
 * API version: 1.0.0
 * Contact: dev-support@insolar.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ResponsesSearchJetidMeta Meta data.
type ResponsesSearchJetidMeta struct {
	// Jet ID.
	JetId string `json:"jet-id,omitempty"`
}
