/*
 * Insolar Block Explorer API
 *
 * BE description 
 *
 * API version: 1.0.0
 * Contact: dev-support@insolar.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ResponsesSearchRecordYamlMeta Meta data.
type ResponsesSearchRecordYamlMeta struct {
	// Record reference.
	RecordRef string `json:"record_ref,omitempty"`
}
