/*
 * Insolar Block Explorer API
 *
 * BE description 
 *
 * API version: 1.0.0
 * Contact: dev-support@insolar.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Record Record representation.
type Record struct {
	// Record reference.
	Reference string `json:"reference,omitempty"`
	// Previous record reference.
	PrevRecordReference string `json:"prev_record_reference,omitempty"`
	// Object reference.
	ObjectReference string `json:"object_reference,omitempty"`
	// Prototype reference.
	PrototypeReference string `json:"prototype_reference,omitempty"`
	// Record type.
	Type string `json:"type,omitempty"`
	// Unix timestamp.
	Timestamp int64 `json:"timestamp,omitempty"`
	// Record payload.
	Payload string `json:"payload,omitempty"`
	// Record hash.
	Hash string `json:"hash,omitempty"`
	// Pulse number.
	PulseNumber int64 `json:"pulse_number,omitempty"`
	// Jet ID.
	JetId string `json:"jet_id,omitempty"`
	// JetDrop ID is concatenation of jet_id and pulse_number.
	JetDropId string `json:"jet_drop_id,omitempty"`
	// Order is the record order number in the Jet Drop.
	Order int64 `json:"order,omitempty"`
	// Index is concatenation of pulse_number and order.
	Index string `json:"index,omitempty"`
}
