/*
 * Insolar Block Explorer API
 *
 * BE description 
 *
 * API version: 1.0.0
 * Contact: dev-support@insolar.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// SearchLifelineMeta Meta data.
type SearchLifelineMeta struct {
	// Object reference.
	ObjectReference string `json:"object_reference,omitempty"`
}
