/*
 * Insolar Block Explorer API
 *
 * BE description 
 *
 * API version: 1.0.0
 * Contact: dev-support@insolar.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// CodeValidationFailures Validation Failure.
type CodeValidationFailures struct {
	// Property name.
	Property string `json:"property,omitempty"`
	// Failure reason.
	FailureReason string `json:"failure_reason,omitempty"`
}
