/*
 * Insolar Block Explorer API
 *
 * BE description 
 *
 * API version: 1.0.0
 * Contact: dev-support@insolar.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ResponsesSearchJetDropMeta Meta data.
type ResponsesSearchJetDropMeta struct {
	// JetDrop ID.
	JetDropId string `json:"jet_drop_id,omitempty"`
}
