/*
 * Insolar Block Explorer API
 *
 * BE description 
 *
 * API version: 1.0.0
 * Contact: dev-support@insolar.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ResponsesSearchLifelineYaml Lifeline response for Search.
type ResponsesSearchLifelineYaml struct {
	// Result type.
	Type string `json:"type,omitempty"`
	Meta ResponsesSearchLifelineYamlMeta `json:"meta,omitempty"`
}
