/*
 * Insolar Block Explorer API
 *
 * BE description 
 *
 * API version: 1.0.0
 * Contact: dev-support@insolar.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ResponsesSearchPulseYamlMeta Meta data.
type ResponsesSearchPulseYamlMeta struct {
	// Pulse Number.
	PulseNumber int64 `json:"pulse_number,omitempty"`
}
