/*
 * Swagger Petstore
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// CreateAPetResponse201 struct for CreateAPetResponse201
type CreateAPetResponse201 struct {
	Code int32 `json:"code"`
	Message string `json:"message"`
}
